title = "gitleaks config"

[extend]
# useDefault will extend the base configuration with the default gitleaks config:
# https://github.com/zricethezav/gitleaks/blob/master/config/gitleaks.toml
useDefault = true

[allowlist]
    description = "Allowlisted files"
    paths = [
    '''.automation/test''',
    '''megalinter-reports''',
    '''.github/linters''',
    '''node_modules''',
    '''.mypy_cache''',
    '''(.*?)gitleaks\.toml$''',
    '''(.*?)package-lock.json$''',
    '''(.*?)(png|jpg|gif|doc|docx|pdf|bin|xls|pyc|zip)$''',
    '''(go.mod|go.sum)$''']

[[rules]]
description = "Password"
id = "password"
regex = '''(?i)(.*password.*|.*pwd.*|.*passwd.*|.*magicword.*)'''
secretGroup = 1
keywords = [
    "password",
    "pwd",
    "passwd",
    "magicword"
]