DISABLE_LINTERS:
  - CSS_SCSS_LINT
  - CSS_STYLELINT
  - HTML_DJLINT
  - JSON_JSONLINT
  - SPELL_CSPELL
  - HTML_HTMLHINT

FILTER_REGEX_EXCLUDE: .*.spec.ts
#APPLY_FIXES: all
#APPLY_FIXES_EVENT: all
ENABLE_LINTERS:
  - TYPESCRIPT_ES