name: Echo Hello
on:
  push:
    branches: [develop]
jobs:
  echo-job:
    runs-on: ubuntu-latest
    steps:
      - name: Echo Hello
        run: echo "Hello"
        id: hello
      - name: Trigger Reusable Workflow
        uses: ./.github/workflows/build.yml
        with:
          message: ${{ steps.hello.outputs.message }}