name: Main Build Workflow

on:
  push:
    branches:
      - develop

jobs:
  release:
    uses: shahXrul/lantern/.github/workflows/build.yml@develop
    with:
      runs-on: "ubuntu-latest"
      node-version: "14.x"
    secrets: inherit