name: Echo Hello
on:
  push:
    branches: [develop]
jobs:
  echo-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Echo Hello
        run: echo "Hello"
        id: hello

