name: Main Build Workflow
on:
  push:
    branches:
      - develop
jobs:
  call-workflow-A:
    uses: shahXrul/lantern/.github/workflows/build.yml@develop
    with:
      username: Houssem
  echo-job1:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Echo Hello
        run: echo "Hello"
        id: hello