name: Main Build Workflow
on:
  push:
    branches:
      - develop
jobs:
  echo-job1:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Install dependecies
        run: |
          cd lanternUi
          npm install

      - name: Build it
        run: |
          cd lanternUi
          npm run build

      - name: Update version
        run: |
          cd lanternUi
          npm version patch -m "chore: bump version to %s"
          git push --follow-tags