name: Main Build Workflow

on:
  workflow_dispatch:
  push:
    branches: ["develop"]

jobs:
  echo-job1:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Echo Hello
        run: echo "Hello"
        id: hello
  call-workflow-A:
    uses: shahXrul/lantern/.github/workflows/build.yml@develop
    with:
      username: Houssem
  call-workflow-B:
    needs: call-workflow-A
    uses: shahXrul/lantern/.github/workflows/build.yml@develop
    with:
      username: Houssem2