name: Main Build Workflow
on:
  push:
    branches:
      - develop
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Echo Hello
        run: echo "Hello from Job 1"
        id: hello_job1
  job2:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Echo Hello
        run: echo "Hello from Job 2"
        id: hello_job2