name: Main Build Workflow
on:
  push:
    branches:
      - develop
jobs:
  echo-job1:
    runs-on: ubuntu-latest
    if: github.actor != 'github-actions[bot]'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Install dependecies
        run: |
          cd lanternUi
          npm install

      - name: Build it
        run: |
          cd lanternUi
          export NODE_OPTIONS=--openssl-legacy-provider
          npm run build

      - name: Get app version
        id: version
        run: |
          cd lanternUi
          echo "{app_version}={$(jq -r '.version' package.json)}" >> $GITHUB_OUTPUT

      - name: Update version
        run: |
          git config --global user.name "github-action[bot]"
          git config --global user.email "github-action[bot]@users.noreply.github.com"
          cd lanternUi
          echo "{app_version_new}={$(npm version patch -m) }" >> $GITHUB_OUTPUT
          #npm version patch -m "chore: bump version to %s"
          sed -i 's/$${steps.version.outputs.app_version}/$$(steps.version.outputs.app_version_new)/g' versions.svg
          git add versions.svg
          git add .
          git commit -m 'increment version'
          git push