name: Main Build Workflow
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  echo-job1:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Echo Hello
        run: echo "Hello from main"
        id: hello
  call-workflow-release:
    environment:
        name: Main
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Echo Hello
        run: echo "Hello from main 2"
        id: hello2