name: Main Build Workflow manual
on:
  pull_request:
    types:
      - closed
    branches:
      - main
  
jobs:
  echo-job1:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Echo Hello
        run: echo "Hello from asd"
        id: hello
  deploy-prod:
    runs-on: ubuntu-latest
    needs: [echo-job1]
    if: github.event.pull_request.merged == true
    environment: 'main'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Echo Hello
        run: echo "Hello from main 2"
        id: hello2