name: Main Build Workflow manual
on:
  push:
    branches:
      - main
  workflow_dispatch:
  
jobs:
  echo-job1:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Echo Hello
        run: echo "Hello from asd"
        id: hello
  deploy-prod:
    runs-on: ubuntu-latest
    needs: [echo-job1]
    if: github.event_name == 'workflow_dispatch'
    environment: 'main'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Echo Hello
        run: echo "Hello from main 2"
        id: hello2